### ISSUE TITLE
Server fails to start with rw.io

### ISSUE THREAD

**Issue by Sitin** [compoundjs/socket#1]
After installing rw.io server failed to start with following error (it seems that railway.controller doesn't have prototype but railway.controller.Controller does):

```
{{path to node}}/node server.js
info: socket.io started
Error while executing {{path to railway}}/npmfile.js

{{path to railway}}/node_modules/railway/lib/railway_utils.js:168
        throw e;
              ^
TypeError: Cannot set property 'socket' of undefined
    at Object.exports.init ({{path to railway}}/node_modules/rw.io/index.js:8:41)
    at ctx.require ({{path to railway}}/node_modules/railway/lib/extensions.js:38:17)
    at {{path to railway}}/npmfile.js:4:1
    at Script.Object.keys.forEach.(anonymous function) [as runInNewContext] (vm.js:41:22)
    at Object.runCode ({{path to railway}}/node_modules/railway/lib/railway_utils.js:165:11)
    at Object.exports.init ({{path to railway}}/node_modules/railway/lib/extensions.js:21:15)
    at Object.initRailway [as init] ({{path to railway}}/node_modules/railway/lib/onrailway.js:111:24)
    at Object.exports.createServer ({{path to railway}}/node_modules/railway/lib/onrailway.js:176:13)
    at Object.<anonymous> ({{path to railway}}/server.js:3:47)
    at Module._compile (module.js:449:26)

Process finished with exit code 1
```

**Comment by 1602** [comment]
FIxed in compound@latest
