### ISSUE TITLE
After adding rw.io to a new compound project, the server crashes on handshake.

### ISSUE THREAD

**Issue by fodor0205** [compoundjs/socket#3]
The client tries to load the following url:
`http://localhost:3000/socket.io/1/?t=1356353788478`
which throws an error on the server:

```
domain.js:66
    throw er;
          ^
TypeError: Cannot call method 'indexOf' of undefined
    at session (/home/feri/wwwroot/test/blog/node_modules/express/node_modules/connect/lib/middleware/session.js:221:30)
    at exports.init.io.sockets.on.hs (/home/feri/wwwroot/test/blog/node_modules/rw.io/index.js:55:13)
    at cookieParser (/home/feri/wwwroot/test/blog/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at Manager.exports.init.io.sockets.on.hs (/home/feri/wwwroot/test/blog/node_modules/rw.io/index.js:53:9)
    at Manager.authorize (/home/feri/wwwroot/test/blog/node_modules/socket.io/lib/manager.js:909:31)
    at Manager.handleHandshake (/home/feri/wwwroot/test/blog/node_modules/socket.io/lib/manager.js:785:8)
    at Manager.handleRequest (/home/feri/wwwroot/test/blog/node_modules/socket.io/lib/manager.js:593:12)
    at Server.<anonymous> (/home/feri/wwwroot/test/blog/node_modules/socket.io/lib/manager.js:119:10)
    at Server.EventEmitter.emit (events.js:99:17)
    at HTTPParser.parser.onIncoming (http.js:1807:12)
```

**Comment by o-nix** [comment]
Is fixed version in the NPM repository?

**Comment by anatoliychakkaev** [comment]
I'm not sure. Just have published it again.
